version: "3"

services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/app/
    links:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/app/

  db:
    image: mysql:5.7
    container_name: mysql-projdocker
    volumes:
      - ./db/:/var/lib/mysql-files
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: formulario-gustavo
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
      # command: mysqld --default-authentication-plugin=mysql_native_password
  phpmyadmin:
    container_name: phpmyamdin-projdocker
    image: phpmyadmin
    links:
      - db
    ports:
      - 8002:80
    environment:
      PMA_HOST: db
